# Generated by Django 5.2.4 on 2025-09-14 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_remove_cloth_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='income',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
